default: &DEFAULT
  consumer_key: BoLeUtxiaeSEoiIvYjuI7LOtu
  consumer_secret: DGP0Mkbjxjq7m68bPmeKHeLZkPjNqptUh8GulYYddFGpyluQeJ
  access_token: 2239665402-XfPQcvuWCsG6eoigbthw7Y0N2zl7Qxd96jYSuAX
  access_secret: hcj1AJNR4RTtIKnBM7gwJUtWeX19FEvaNfVgVzYq3qcPa

twitter:
  development: 
    <<: *DEFAULT
  test:
    <<: *DEFAULT
  staging:
    <<: *DEFAULT
  production:
    <<: *DEFAULT
